{% set name = "aws-c-cal" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awslabs/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 52df95150a8548ac35a0e4b6f59fbdebff27e4124c0b7e5eaa969ed3ba62fc82

build:
  number: 1
  run_exports:
    - {{ pin_subpackage("aws-c-cal", max_pin="x.x.x") }}

requirements:
  build:
    - cmake !=3.19.0,!=3.19.1
    - {{ compiler('c') }}
    - ninja
  host:
    - aws-c-common
    - openssl

test:
  commands:
    - test -f $PREFIX/lib/libaws-c-cal${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/aws/cal/cal.h  # [unix]
    - if not exist %LIBRARY_INC%\\aws\\cal\\cal.h exit 1          # [win]
    - if not exist %PREFIX%\\Library\\bin\\aws-c-cal.dll exit 1  # [win]

about:
  home: https://github.com/awslabs/aws-c-cal
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Aws Crypto Abstraction Layer: Cross-Platform, C99 wrapper for cryptography primitives.'

extra:
  recipe-maintainers:
    - xhochy
    - conda-forge/aws-sdk-cpp
